
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../touch/src",
  "Ext.data.ProxyMgr": "../../touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "../../touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../touch/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.Entry": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileEntry": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileSystem": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../touch/src/draw/engine/SvgContext.js",
  "FindACab": "app",
  "Utils": "utils"
});
Ext.ClassManager.addNameAlternateMappings({
  "FindACab.controller.CabController": [],
  "FindACab.controller.SettingsController": [],
  "FindACab.model.Cab": [],
  "FindACab.model.Setting": [],
  "FindACab.store.Cabs": [],
  "FindACab.store.Ratings": [],
  "FindACab.store.Settings": [],
  "FindACab.view.DetailView": [],
  "FindACab.view.Main": [],
  "FindACab.view.Overview": [],
  "FindACab.view.RatingChart": [],
  "FindACab.view.SettingsView": [],
  "Utils.Commons": []
});
Ext.ClassManager.addNameAliasMappings({
  "FindACab.controller.CabController": [],
  "FindACab.controller.SettingsController": [],
  "FindACab.model.Cab": [],
  "FindACab.model.Setting": [],
  "FindACab.store.Cabs": [],
  "FindACab.store.Ratings": [],
  "FindACab.store.Settings": [],
  "FindACab.view.DetailView": [
    "widget.detailview"
  ],
  "FindACab.view.Main": [],
  "FindACab.view.Overview": [
    "widget.overview"
  ],
  "FindACab.view.RatingChart": [
    "widget.ratingchart"
  ],
  "FindACab.view.SettingsView": [
    "widget.settingsview"
  ],
  "Utils.Commons": []
});
