
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../touch/src",
  "Ext.data.ProxyMgr": "../../touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "../../touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../../touch/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../../touch/src/device/sqlite/Sencha.js",
  "Ext.device.filesystem.DirectoryEntry": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.Entry": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileEntry": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.device.filesystem.FileSystem": "../../touch/src/device/filesystem/HTML5.js",
  "Ext.draw.engine.SvgContext.Gradient": "../../touch/src/draw/engine/SvgContext.js",
  "FindACab": "app"
});
Ext.ClassManager.addNameAlternateMappings({
  "FindACab.view.Main": []
});
Ext.ClassManager.addNameAliasMappings({
  "FindACab.view.Main": [
    "widget.main"
  ]
});
